language: java
install:
- wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
- mkdir spigot
- mv BuildTools.jar ./spigot/
- cd spigot
- java -jar BuildTools.jar --rev 1.12.2
- mkdir lib
- cd ..
- cp spigot-1.12.2.jar ../lib/spigot.jar
- ant build
os: linux
jdk:
- oraclejdk8
- openjdk8
sudo: false
addons:
    apt:
        packages:
        - maven
        - ant
        - git
branches:
        only:
        - master
