language: java
install:
- mkdir lib
- wget https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot-api/1.12.2-R0.1-SNAPSHOT/spigot-api-1.12.2-R0.1-20180627.103100-152.jar -O ./lib/spigot.jar
- wget https://repo.maven.apache.org/maven2/commons-io/commons-io/2.6/commons-io-2.6.jar -O ./lib/commons-io.jar
script:
- ant build
os: linux
jdk:
- oraclejdk8
- openjdk8
- oraclejdk9
- openjdk9
sudo: false
branches:
    only:
    - master
