language: java
install:
- mkdir lib
- wget https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot-api/1.12.2-R0.1-SNAPSHOT/spigot-api-1.12.2-R0.1-20180617.030601-148.jar -O ./lib/spigot.jar
script: ant build
os: linux
jdk:
- oraclejdk8
- openjdk8
sudo: false
branches:
        only:
        - master
