name: Magna
version: 0.0.0
author: MoriGM

main: de.morigm.magna.Main

commands:
      fly:
      godmode:
      mute:
      heal:
      getworld:
      setitemname:
      ip:
      tpall:
      itemhead:
      cmdspy:
      magna-reloadconfig:
      getpos:
      setwarp:
      getwarp:
      removewarp:
      warp:
      warps:
      kickall:
      memorie:
      chatclear:
      allchatclear:
      magna-groups:
      magna-id:
      magna-list: