name: Magna
version: 0.4.0
author: MoriGM

main: de.morigm.magna.Main

commands:
      fly:
      godmode:
      mute:
      heal:
      getworld:
      setitemname:
      ip:
      tpall:
      itemhead:
      cmdspy:
      magna-reloadconfig:
      getpos:
      setwarp:
      getwarp:
      removewarp:
      warp:
      warps:
      kickall:
      memorie:
      chatclear:
      allchatclear:
      magna-groups:
      magna-id:
      magna-list:
      magna-group-exec:
      teamchat:
      setspawn:
      spawn:
      day:
      night:
      broadcast:
      gamemodeinfo:
      repair:
      ops:
      bans:
      banips:
      skull: